# script which sorts S3 folders by increasing size

# go to the directory when the script is located
cd $(dirname $0)

# get accessions file from config.txt and read them into array
FNAME=`cat config.txt | grep accession_file | cut -d"=" -f2`
readarray FOLDERS < $FNAME

# loop over accession names and get size of each corresponding folder in S3
NLINES=`wc -l $FNAME | cut -d" " -f1`
COUNTER=0
while [[ $COUNTER -lt $NLINES ]]; do
  SIZES[COUNTER]=`aws s3 ls s3://budgies/arrayexpress2/${FOLDERS[COUNTER]} --recursive  | grep -v -E "(Bucket: |Prefix: |LastWriteTime|^$|--)" | awk 'BEGIN {total=0}{total+=$3}END{print total/1024/1024}'`
  COUNTER=$COUNTER+1
done

# save folder sizes in text file
echo ${SIZES[@]} > sizes.txt

# make text file containing folder names sorted by size in ascending order
python3 sort_s3_folders.py

# remove file generated by the scripts
rm sizes.txt
